# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-10 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_people', '0020_auto_20190110_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='show on website'),
        ),
    ]
