# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-10 17:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('aldryn_people', '0021_person_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='second_phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='secondary phone'),
        ),
        migrations.AddField(
            model_name='person',
            name='second_visual',
            field=filer.fields.image.FilerImageField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_person_visual', to=settings.FILER_IMAGE_MODEL),
        ),
    ]
