# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-11 08:01
from __future__ import unicode_literals

import aldryn_categories.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_categories', '0004_auto_20150623_0859'),
        ('aldryn_people', '0022_auto_20190110_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='categories',
            field=aldryn_categories.fields.CategoryManyToManyField(blank=True, to='aldryn_categories.Category', verbose_name='categories'),
        ),
    ]
