# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-14 17:27
from __future__ import unicode_literals

import aldryn_translation_tools.models
from django.db import migrations, models
import django.db.models.deletion
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_people', '0023_person_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, verbose_name='address')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='postal code')),
                ('city', models.CharField(blank=True, max_length=255, verbose_name='city')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='phone')),
                ('fax', models.CharField(blank=True, max_length=100, null=True, verbose_name='fax')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='email')),
                ('website', models.URLField(blank=True, null=True, verbose_name='website')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('lng', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('is_published', models.BooleanField(default=True, verbose_name='show on website')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
            bases=(aldryn_translation_tools.models.TranslationHelperMixin, aldryn_translation_tools.models.TranslatedAutoSlugifyMixin, parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LocationTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=255, verbose_name='Display name')),
                ('slug', models.SlugField(blank=True, default='', help_text='Leave blank to auto-generate a unique slug.', max_length=255, verbose_name='slug')),
                ('office', models.CharField(blank=True, max_length=255, verbose_name='Office name')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='aldryn_people.Location')),
            ],
            options={
                'verbose_name': 'Location Translation',
                'db_table': 'aldryn_people_location_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.AlterField(
            model_name='person',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aldryn_people.Location', verbose_name='location'),
        ),
        migrations.AlterUniqueTogether(
            name='locationtranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
