# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-28 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_people', '0024_auto_20190114_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persontranslation',
            name='first_name',
            field=models.CharField(default='', help_text="Provide this person's first name.", max_length=255, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='persontranslation',
            name='last_name',
            field=models.CharField(default='', help_text="Provide this person's last name.", max_length=255, verbose_name='last name'),
        ),
    ]
