# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-24 08:09
from __future__ import unicode_literals

import aldryn_common.admin_fields.sortedm2m
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djangocms_icon.fields
import filer.fields.image
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_categories', '0007_categorytranslation_landing_page'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('cms', '0020_old_tree_cleanup'),
        ('aldryn_people', '0024_auto_20190114_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedPeoplePlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='+', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Title')),
                ('icon', djangocms_icon.fields.Icon(blank=True, default='fa-', max_length=255, verbose_name='Icon')),
                ('number_of_people', models.PositiveSmallIntegerField(verbose_name='Number of people')),
                ('layout', models.CharField(max_length=30, verbose_name='layout')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_image', to=settings.FILER_IMAGE_MODEL)),
                ('related_categories', aldryn_common.admin_fields.sortedm2m.SortedM2MModelField(blank=True, help_text=None, to='aldryn_categories.Category', verbose_name='related categories')),
                ('related_groups', aldryn_common.admin_fields.sortedm2m.SortedM2MModelField(blank=True, help_text=None, to='aldryn_people.Group', verbose_name='related groups')),
                ('related_locations', aldryn_common.admin_fields.sortedm2m.SortedM2MModelField(blank=True, help_text=None, to='aldryn_people.Location', verbose_name='related locations')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.AlterField(
            model_name='person',
            name='groups',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, default=None, help_text='Choose and order the groups for this person, the first will be the "primary group".', related_name='people', to='aldryn_people.Group'),
        ),
        migrations.AlterField(
            model_name='persontranslation',
            name='first_name',
            field=models.CharField(default='', help_text="Provide this person's first name.", max_length=255, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='persontranslation',
            name='last_name',
            field=models.CharField(default='', help_text="Provide this person's last name.", max_length=255, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='relatedpeopleplugin',
            name='related_people',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='aldryn_people.Person', verbose_name='key people'),
        ),
    ]
