# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-21 06:15
from __future__ import unicode_literals

import cms.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
        ('aldryn_people', '0026_person_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='placeholder_sidebar',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname='sidebar', to='cms.Placeholder'),
        ),
    ]
