# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-14 05:56
from __future__ import unicode_literals

import aldryn_common.admin_fields.sortedm2m
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('js_services', '0001_initial'),
        ('aldryn_people', '0027_person_placeholder_sidebar'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatedpeopleplugin',
            name='related_services',
            field=aldryn_common.admin_fields.sortedm2m.SortedM2MModelField(blank=True, help_text=None, to='js_services.Service', verbose_name='related services'),
        ),
    ]
