# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-21 08:04
from __future__ import unicode_literals

from django.db import migrations

def resave_for_placeholder_rendering(apps, schema_editor):
    # Resave for PlaceholderField Rendering
    # Person = apps.get_model('aldryn_people', 'Person')
    # for person in Person.objects.all():

    #     person.save()
    # must be a "Placeholder" instance.


    Person = apps.get_model('aldryn_people', 'Person')

    from cms.models import Placeholder
    placeholder_name = 'placeholder_sidebar'
    placeholder_id_name = '{0}_id'.format(placeholder_name)

    for person in Person.objects.all():
        placeholder_id = getattr(person, placeholder_id_name, None)
        if placeholder_id is not None:
            continue
        placeholder_new = Placeholder.objects.create(slot=placeholder_name)
        setattr(person, placeholder_id_name, placeholder_new.pk)

        person.save()

def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_people', '0028_relatedpeopleplugin_related_services'),
    ]

    operations = [
        migrations.RunPython(resave_for_placeholder_rendering, backwards),
    ]
