# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-25 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_people', '0029_resave_for_placeholderfield_rendering'),
    ]

    operations = [
        migrations.AddField(
            model_name='persontranslation',
            name='suffix',
            field=models.CharField(blank=True, default='', help_text="Provide this person's suffix.", max_length=60, verbose_name='last name'),
        ),
    ]
