# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-05 09:05
from __future__ import unicode_literals

import cms.models.fields
from django.db import migrations
import django.db.models.deletion

def resave_for_placeholder_rendering(apps, schema_editor):
    # Resave for PlaceholderField Rendering
    # Person = apps.get_model('aldryn_people', 'Person')
    # for person in Person.objects.all():

    #     person.save()
    # must be a "Placeholder" instance.


    Person = apps.get_model('aldryn_people', 'Person')

    from cms.models import Placeholder
    placeholder_name = 'content'
    placeholder_id_name = '{0}_id'.format(placeholder_name)

    for person in Person.objects.all():
        placeholder_id = getattr(person, placeholder_id_name, None)
        if placeholder_id is not None:
            continue
        placeholder_new = Placeholder.objects.create(slot=placeholder_name)
        setattr(person, placeholder_id_name, placeholder_new.pk)

        person.save()

def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
        ('aldryn_people', '0030_persontranslation_suffix'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='content',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_content', slotname='content', to='cms.Placeholder'),
        ),
        migrations.RunPython(resave_for_placeholder_rendering, backwards),
    ]
