# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-30 07:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_people', '0035_auto_20190429_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='companies',
        ),
        migrations.RemoveField(
            model_name='relatedpeopleplugin',
            name='related_companies',
        ),
    ]
