# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-28 16:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_people', '0036_auto_20190430_0747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persontranslation',
            old_name='first_name',
            new_name='first_name_trans',
        ),
        migrations.RenameField(
            model_name='persontranslation',
            old_name='last_name',
            new_name='last_name_trans',
        ),
    ]
