# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-28 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_people', '0037_rename_names_out_of_the_way'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='first_name',
            field=models.CharField(default='', help_text="Provide this person's first name.", max_length=255, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='person',
            name='last_name',
            field=models.CharField(default='', help_text="Provide this person's last name.", max_length=255, verbose_name='last name'),
        ),
    ]
