# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-30 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_people', '0039_data_migration_trans_names_to_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='sorting',
            field=models.PositiveSmallIntegerField(default=1, help_text='first with low value', verbose_name='sorting field'),
        ),
    ]
