# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-28 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_people', '0041_persontranslation_search_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatedpeopleplugin',
            name='more_button_is_shown',
            field=models.BooleanField(default=False, verbose_name='Show “See More Button”'),
        ),
        migrations.AddField(
            model_name='relatedpeopleplugin',
            name='more_button_link',
            field=models.CharField(blank=True, max_length=255, verbose_name='See More Button Link'),
        ),
        migrations.AddField(
            model_name='relatedpeopleplugin',
            name='more_button_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='See More Button Text'),
        ),
    ]
