# Generated by Django 2.2.9 on 2020-01-29 19:25

import app_data.fields
import cms.models.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import filer.fields.image
import parler.fields
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('aldryn_people', '0043_auto_20190709_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='app_data',
            field=app_data.fields.AppDataField(default='{}', editable=False),
        ),
        migrations.AddField(
            model_name='group',
            name='namespace',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, null=True, verbose_name='Instance namespace'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='type',
            field=models.CharField(default='aldryn_people.Group', max_length=100, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='person',
            name='banner',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_banner', slotname='person_banner', to='cms.Placeholder'),
        ),
        migrations.AddField(
            model_name='person',
            name='canonical_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Canonical URL'),
        ),
        migrations.AddField(
            model_name='person',
            name='xing',
            field=models.URLField(blank=True, null=True, verbose_name='xing'),
        ),
        migrations.AlterField(
            model_name='grouptranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='aldryn_people.Group'),
        ),
        migrations.AlterField(
            model_name='peopleplugin',
            name='people',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text='Select and arrange specific people, or, leave blank to select all.', to='aldryn_people.Person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='js_locations.Location', verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='persontranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='aldryn_people.Person'),
        ),
        migrations.AlterField(
            model_name='relatedpeopleplugin',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_image', to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AlterField(
            model_name='relatedpeopleplugin',
            name='more_button_is_shown',
            field=models.BooleanField(blank=True, default=False, verbose_name='Show “See More Button”'),
        ),
        migrations.AlterField(
            model_name='relatedpeopleplugin',
            name='related_categories',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='aldryn_categories.Category', verbose_name='related categories'),
        ),
        migrations.AlterField(
            model_name='relatedpeopleplugin',
            name='related_groups',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='aldryn_people.Group', verbose_name='related groups'),
        ),
        migrations.AlterField(
            model_name='relatedpeopleplugin',
            name='related_locations',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='js_locations.Location', verbose_name='related locations'),
        ),
        migrations.AlterField(
            model_name='relatedpeopleplugin',
            name='related_services',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='js_services.Service', verbose_name='related services'),
        ),
    ]
