# Generated by Django 2.2.9 on 2020-01-29 19:25

import app_data.fields
import cms.models.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import filer.fields.image
import parler.fields
import sortedm2m.fields


def gen_uuid(apps, schema_editor):
    Group = apps.get_model('aldryn_people', 'group')
    for row in Group.objects.all():
        row.namespace = django.utils.timezone.now()
        row.save(update_fields=['namespace'])

class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_people', '0044_auto_20200129_1925'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='group',
            name='namespace',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, unique=True, verbose_name='Instance namespace'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('type', 'namespace')},
        ),
    ]
