# Generated by Django 2.2.10 on 2020-03-05 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_people', '0045_auto_20200129_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='persontranslation',
            name='is_published_trans',
            field=models.BooleanField(default=True, verbose_name='show on website'),
        ),
    ]
