# Generated by Django 2.2.10 on 2020-05-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_people', '0046_persontranslation_is_published_trans'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='details_enabled',
            field=models.BooleanField(default=True, verbose_name='enable details'),
        ),
    ]
