# Generated by Django 2.2.13 on 2020-06-25 23:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_people', '0047_person_details_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='custom_fields_settings',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='custom_fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
