# Generated by Django 2.2.13 on 2020-08-14 08:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_people', '0048_auto_20200625_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='custom_fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
