# Generated by Django 2.2.27 on 2022-04-07 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_people', '0049_group_custom_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='persontranslation',
            name='layout_trans',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='layout'),
        ),
    ]
