# Generated by Django 2.2.24 on 2022-04-14 10:59

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('aldryn_people', '0050_persontranslation_layout_trans'),
    ]

    operations = [
        migrations.AddField(
            model_name='persontranslation',
            name='second_visual_trans',
            field=filer.fields.image.FilerImageField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_person_visual_trans', to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AddField(
            model_name='persontranslation',
            name='visual_trans',
            field=filer.fields.image.FilerImageField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL),
        ),
    ]
